require('plugins.dracula')
require('plugins.treesitter')
require('plugins.lspconfigs')
require('plugins.cmp')
require('plugins.identblankline')
require('plugins.whichkey')
require('plugins.lualine')
require('plugins.nvimtree')
